# Used
gemini_api_key = "AIzaSyCfJx-6MrbOxz_N6TO5ETqwV_UH33Ru-ro"
exchange_api_key = "b8fd64b9635a93290b094923"
mongodb_uri = "mongodb+srv://webappstreamer_db_user:JVU8B2PwgRcGaCLr@cluster0.aihg5j0.mongodb.net/?appName=Cluster0"
# Not used
Trip_Builder_pass = 5555
Admin_code = "Mohamed+Diaa_Eldin_Mohamrt0987654321mondbo"
